### ISSUE TITLE
无法正常配置

### ISSUE THREAD

**Issue by ZehuanZhang** [fotomxq/OA-SYS#3]
运行环境已经配置完成，但是登录时显示
Location : core-db::connect()::PDOException

Message : Connect Database error.

Level : 1
目前已经反复确认过数据库名称、密码和其他设置，均无问题；
版本信息：
mysql: Ver 14.14 Distrib 5.7.24
php: 7.3.0RC5 (cli)
apache2: Apache/2.4.18

**Comment by fotomxq** [comment]
你好，麻烦提供一下详细错误信息，包括mysql和php部分的错误信息。

这系统是N年前开发的，当时使用的php版本较低，所以不排除PDO接口改变引起错误问题，但概率不大。问题可能还是出在PHP部分。
1、**出现这种故障还有一个原因，是权限不足。**
你那边是否在linux下运行？这个需要给权限，尤其是配置文件读写权限。
2、**mysql与php是否通讯正常？**
如果可以，麻烦单独运行OA-SYS/includes/core-db.php文件内的102行代码connect函数，给予dns、username、password三个参数试一下是否可行？或将pdo单独在任意一个php文件内运行，看是否可以是正常与mysql通讯。
